<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BaconQrCode\Encoder\MatrixUtil'        => __DIR__ . '/src/BaconQrCode/Encoder/MatrixUtil.php',
    'BaconQrCode\Encoder\Encoder'           => __DIR__ . '/src/BaconQrCode/Encoder/Encoder.php',
    'BaconQrCode\Encoder\QrCode'            => __DIR__ . '/src/BaconQrCode/Encoder/QrCode.php',
    'BaconQrCode\Encoder\ByteMatrix'        => __DIR__ . '/src/BaconQrCode/Encoder/ByteMatrix.php',
    'BaconQrCode\Encoder\BlockPair'         => __DIR__ . '/src/BaconQrCode/Encoder/BlockPair.php',
    'BaconQrCode\BitArray'                  => __DIR__ . '/src/BaconQrCode/BitArray.php',
    'BaconQrCode\Mode'                      => __DIR__ . '/src/BaconQrCode/Mode.php',
    'BaconQrCode\ReedSolomon\Encoder'       => __DIR__ . '/src/BaconQrCode/ReedSolomon/Encoder.php',
    'BaconQrCode\ReedSolomon\GenericGfPoly' => __DIR__ . '/src/BaconQrCode/ReedSolomon/GenericGfPoly.php',
    'BaconQrCode\ReedSolomon\GenericGf'     => __DIR__ . '/src/BaconQrCode/ReedSolomon/GenericGf.php',
    'BaconQrCode\Version'                   => __DIR__ . '/src/BaconQrCode/Version.php',
    'BaconQrCode\AbstractEnum'              => __DIR__ . '/src/BaconQrCode/AbstractEnum.php',
    'BaconQrCode\ErrorCorrectionLevel'      => __DIR__ . '/src/BaconQrCode/ErrorCorrectionLevel.php',
);